branch-defaults:
  default:
    environment: Yourdev-env
environment-defaults:
  Yourdev-env:
    branch: null
    repository: null
global:
  application_name: yourdev
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
